[] execVM "globalScripts\Pie_RespawnHelper.sqf";

[setupLaptop, loadoutBox] execVM "globalScripts\Pie_Helper_DynamicPlayerFaction.sqf";

[setupLaptop, [
	["European Locals", "CSAR\EuroLocals", "PIE_LocalEuro"],
	["FIA", "CSAR\FIA", "IND_G_F"],
	["Russian (Heavy)", "CSAR\RussianHeavy", "CUP_O_RU"],
	["Takistan Locals", "CSAR\TakiLocals", "CUP_I_TK_GUE"]
]] execVM "globalScripts\DynamicFactions\Pie_DynamicDMPFactionSelector.sqf";

[] execVM "globalScripts\Pie_Helper_AIGunnerDownReaction.sqf";

if(isServer) then
{
	[] execVM "globalScripts\Pie_Helper_BaseSafeZoneMarker.sqf";
	[hostage, wreckToSpawn] execVM "globalScripts\Missions\CSAR\Pie_CSAR.sqf";
};

// Clear task descriptions generated by DMP
player addEventHandler ["TaskSetAsCurrent", {
	params ["_unit", "_task"];
	_retTask = player call BIS_fnc_taskCurrent;

	_desc = _retTask call BIS_fnc_taskDescription;

	if(count _desc > 0) then
	{
		[_retTask, ["", _desc select 1, _desc select 2]] call BIS_fnc_taskSetDescription;
	};
}];